name: Hologram
version: ${project.version}
main: org.sean.hologram
authors: [CombatSandvich]
description: A lightweight plugin to create holograms in Spigot servers.
website: https://seancornell.io
commands:
  hologram:
  mlhologram:
  holocolors:
